### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by sarkarrajj** [girino/CryptoDice#1]
Attention: The database version does not match the code version. Please run "php update_db.php".
Domain name plz check it revert me
dicebitcoin.dicecoin.in

**Comment by girino** [comment]
did you run "php update_db.php"?

**Comment by sarkarrajj** [comment]
Sir I will provide you my ftp user and password
You can check it

**Comment by girino** [comment]
I do not provide this kind of support. If you find bugs on the code, please post here. I am closing this issue since it is not code related.

**Comment by sarkarrajj** [comment]
Sir can you tel me what I had to update in db

**Comment by girino** [comment]
Please follow the instalation instructions on the README.md file.
